### ISSUE TITLE
小米14最新版本升级崩溃

### ISSUE THREAD

**Issue by byjjack** [lovegaoshi/azusa-player-mobile#411]
这是错误信息

java.lang.IllegalArgumentException: Could not convert class android.os.UserHandle
	at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:320)
	at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:316)
	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1240)
	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1160)
	at com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$1(ReactInstanceManager.java:1123)
	at com.facebook.react.ReactInstanceManager.$r8$lambda$gb653mFZ5g89YrL4JOidj7UzBRU(Unknown Source:0)
	at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda4.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by lovegaoshi** [comment]
这个apk能用吗
https://github.com/lovegaoshi/azusa-player-mobile/releases/download/dev-build-2024-05-09/app-arm64-v8a-release.apk

**Comment by byjjack** [comment]
好的

**Comment by byjjack** [comment]
这个还是不能用

**Comment by byjjack** [comment]
老版本可以

**Comment by lovegaoshi** [comment]
麻烦再试一下这个apk
https://github.com/lovegaoshi/azusa-player-mobile/releases/download/dev-build-2024-05-10/app-arm64-v8a-release.apk

**Comment by Solawhite** [comment]
> 麻烦再试一下这个apk https://github.com/lovegaoshi/azusa-player-mobile/releases/download/dev-build-2024-05-10/app-arm64-v8a-release.apk

同样的问题，也是小米，系统版本是`HyperOS1.0.2.0UKACNXM`，报错日志完全相同，这两个apk都是打开闪退，但是长按进入安全模式都可以正常打开，没有测试过旧版本。

**Comment by Solawhite** [comment]
似乎是react-native的问题，在https://github.com/wix/react-native-notifications/issues/287
有提及，也与小米设备有关，不确定这个链接是否有帮助，https://github.com/facebook/react-native/issues/28461

**Comment by lovegaoshi** [comment]
好像懂了但是懂了又不可能，大概半小时后编译完成 再麻烦再试试release下最新的dev版本

**Comment by Solawhite** [comment]
[dev-build-2024-05-11](https://github.com/lovegaoshi/azusa-player-mobile/tree/dev-build-2024-05-11) 可以正常打开了，不会闪退.
> 但是首次打开播放Favorite的第一首似乎会一直卡在加载，我再详细测试下是不是bug。

**Comment by lovegaoshi** [comment]
这个好解决
麻烦贴一下开发者选项里的日志 没有的话把日志等级改为调试

**Comment by Solawhite** [comment]
改了debug，没有日志输出，跟第一首是什么歌曲没有关系，切换下就能播放了，我录了个视频。

https://github.com/lovegaoshi/azusa-player-mobile/assets/32129243/85655b0e-050f-457e-a79d-b96dc84b3b69

**Comment by lovegaoshi** [comment]
因为APM退出的时候记录的上次播放是月茶会（有紫色背景条）；根据逻辑点击正在播放的歌曲时，啥也不会做
但是这首歌又没有实际播放，所以就有这种现象
我应该知道问题所在，最爱歌单这玩意儿我不怎么用 所以坏了。会近期修复

**Comment by lovegaoshi** [comment]
看样子修复咯！
如果 https://github.com/lovegaoshi/azusa-player-mobile/releases/download/dev-build-2024-05-12/app-arm64-v8a-release.apk 问题复现 请再打开这个事情
